server:
  port: 8080
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: admin-configuration
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/**
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/admin/get-configuration, /admin/get-configuration
            - RewritePath=/api/admin/change-configuration, /admin/change-configuration
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

        - id: token-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/get-**
          filters:
            - RewritePath=/api/get-token, /get-token
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

        - id: url-shortner
          uri: http://localhost:8082
          predicates:
            - Path=/api/**
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/create/bulk, /bulk-create
            - RewritePath=/api/create, /create
            - RewritePath=/api/expire/(?<segment>.*), /expire/$\{segment}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
